Test script read username and password from GITHUB Secret dynamically while running test
ortelius/testing pull request #4
Opened 2022-01-07 11:19 UTC by poovaraj

List of changes:

- Test script read username and password from GITHUB Secret dynamically while running test

Precondition :

Create Username and Password and update below repository secret (Refer Screenshot)

> ORTELIUS_APP_USERNAME
> ORTELIUS_APP_PASSWORD

![image](https://user-images.githubusercontent.com/18280543/148536083-b9a35de6-5db5-4b1b-8830-20c9ba81778d.png)

- Username and Password removed from serenity.properteis file for security purpose
- Updated feature file name based on functionality
- Added Thread count 3 in POM.xml file

2022-01-07 12:05 UTC, markyjackson-taulia approved these changes

2022-01-07 12:06 UTC, markyjackson-taulia requested changes
Conflicts must be resolved

2022-01-14 11:29 UTC, poovaraj commented
I don't have write access to update conflicts changes.   Please provide write access

2022-01-18 04:59 UTC, poovaraj commented
I have fixed merge conflict.  Please merge it and create a username and password in Repository SECRECT


List of changes:

Test script read username and password from GITHUB Secret dynamically while running test
Precondition :

Create Username and Password and update below repository secret (Refer Screenshot)

ORTELIUS_APP_USERNAME
ORTELIUS_APP_PASSWORD

2022-01-18 12:45 UTC, markyjackson-taulia approved these changes

2022-01-19 14:49 UTC, merged